#!/usr/bin/python

from __future__ import absolute_import, print_function, unicode_literals

from optparse import OptionParser, make_option
import dbus
import dbus.mainloop.glib
import json
try:
  from gi.repository import GObject
except ImportError:
  import gobject as GObject
import bluezutils

adapter = {}
mainloop = {}
TIMEOUT = 20000

def handler():
	adapter.StopDiscovery()
	mainloop.quit()
	response = {}
	print(json.dumps(response))

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
	GObject.timeout_add(TIMEOUT, handler)

	bus = dbus.SystemBus()

	adapter = bluezutils.find_adapter()

	scan_filter = dict()

	adapter.SetDiscoveryFilter(scan_filter)
	adapter.StartDiscovery()

	mainloop = GObject.MainLoop()
	mainloop.run()