#!/bin/sh


# Get MAC address in the HEX format
MAC=0x$(cat /sys/class/net/eth0/address|awk -F ":" '{print $4""$5""$6}'| tr a-z A-Z)

# Remove the leading nibble 0xC
MAC=$((MAC-0xC00000))

# Convert decimal to an order number
MAC=$(($((MAC+2))/3))

# Set series
SERIES=GN

# Pad the order number and concat it with the series
NAME=$SERIES$(printf %08d $MAC)

# Set all friendly names
uci set system.@system[0].hostname="$NAME"
uci set wireless.ap.ssid="$NAME"
uci commit

sed '/Name=.*/d' /etc/bluetooth/main.conf > /tmp/test.txt
echo Name=$NAME >> /tmp/test.txt
cp /tmp/test.txt /etc/bluetooth/main.conf

sed '/friendly_name=.*/d' /usr/share/miniupnpd/miniupnpd.manufacture.conf > /tmp/test.txt
echo friendly_name=$NAME >> /tmp/test.txt
cp /tmp/test.txt /usr/share/miniupnpd/miniupnpd.manufacture.conf

/etc/init.d/network restart
/etc/init.d/miniupnpd restart