#!/bin/sh /etc/rc.common

START=101
STOP=151

start() {
        /usr/share/lede-ecr-util/checkWanStatus &
        # commands to launch application
}

boot() {
        start
}

stop() {
        echo stop
        # commands to kill application
}