#!/bin/sh
exit 0
if [ "${INTERFACE}" = "usb0" ];
    then if [ "${ACTION}" = "add" ];
        then
                echo "" > /tmp/dhcp.leases
#                /etc/init.d/dnsmasq restart &
         fi
fi

if [ "$ACTION" = "add" ] && [ "$INTERFACE" != "usb0" ]; then
       /bin/bash /root/usb-hotplug "$INTERFACE"
fi
